### ISSUE TITLE
Kafka input and output connectors removed from `benthos list`

### ISSUE THREAD

**Issue by SDBlackwood** [redpanda-data/benthos#79]
I see that when running `benthos list | rg kafka`, kafka is not present on 4.35.0.  Also trying `benthos create http_server//kafka` produces: `unrecognised output type 'kafka'`.  

What is the status of this repo versus the `https://github.com/redpanda-data/connect` one? Are the kafka connectors being removed from here?

**Comment by mihaitodor** [comment]
Hey @SDBlackwood 👋 It's covered in this [blog post](https://www.redpanda.com/blog/redpanda-connect), but the short version is that the original repo has been renamed to https://github.com/redpanda-data/connect and the core Benthos library has been pulled out and moved into this repo which retains the original MIT license and a few core IO components, such as the HTTP ones. The rest of the 3rd party components, such as the Kafka ones, will remain in the Connect repo I linked and most of them have been relicensed to Apache 2 and a few of them to the Redpanda Enterprise license.

**Comment by SDBlackwood** [comment]
Thanks for that @mihaitodor
